### ISSUE TITLE
No public init in generated Swift classes

### ISSUE THREAD

**Issue by chrisvis** [apollostack/apollo-codegen#15]
Hi,

When a query does not have any variables, the generated `GraphQLQuery` class does not contain a public init.
This prevents initialising an instance outside of the module.
You can see this in the StarWars Playground when using `HeroNameQuery()`:

**Playground execution failed: error: StarWarsAPI.playground:4:21: error: 'HeroNameQuery' initializer is inaccessible due to 'internal' protection level
client.fetch(query: HeroNameQuery()) { (result, error) in**

The ParseQueryResponseTests however don’t catch this issue since there, the StarWars API is local, inside the ApolloTests module.
Is this by design, or should the queries be available outside of the module as well?

Possible fix is emitting an empty init for operations without variables :

```diff
diff --git a/src/swift/codeGeneration.js b/src/swift/codeGeneration.js
index cc415fd..ea0b2a9 100644
--- a/src/swift/codeGeneration.js
+++ b/src/swift/codeGeneration.js
@@ -126,6 +126,8 @@ export function classDeclarationForOperation(
           `]`
         ));
       });
+    } else {
+      initializerDeclarationForProperties(generator, []);
     }

     structDeclarationForSelectionSet(
```

**Comment by martijnwalraven** [comment]
No, this is not by design, good catch! Your fix looks good to me. Would you mind opening a PR so I can merge it?

**Comment by chrisvis** [comment]
Opened PR #16
