### ISSUE TITLE
Flow codegen

### ISSUE THREAD

**Issue by rricard** [apollostack/apollo-codegen#2]
We could generate Flow types for the GraphQL queries in the project in parallel of something like [graphql-document-collector](https://github.com/rricard/graphql-document-collector) to get the query docs globally.

I'll work on this in a folder parallel to the `swift/` folder.

**Comment by stubailo** [comment]
Do you use Flow or TypeScript in your project? I'd suggest starting with the one you plan to use yourself, and doing the other second.

**Comment by rricard** [comment]
@stubailo I actually use both (depends on the project: big one is flow, smaller ones is TS). However migrating from one syntax to one another is dead simple. Writing the flow codegen after ts will be super-simple.

**Comment by martijnwalraven** [comment]
@rricard: I don't have any experience with Flow yet, and I don't really understand what is going on here, but the recent `$ObjMap` type constructor might be relevant to this: 
https://twitter.com/andreypopp/status/782192355206135808
https://gist.github.com/gabro/bb83ed574690645053b815da2082b937

**Comment by rricard** [comment]
@martijnwalraven this looks cool but we don't need that actually. Standard types that look like very much like ts interfaces!

**Comment by rricard** [comment]
WIP in #5
