### ISSUE TITLE
[Swift] Generate is producing errors.

### ISSUE THREAD

**Issue by jtwigg** [apollostack/apollo-codegen#20]
I'm generating swift using the default startwars scheme.json. Its failing to produce output. 
scheme.json is attached.

```
apollo-codegen generate **/*.graphql --schema schema.json --output API.swift
```

produces the error:
```
Apollo iOS does not support anonymous operations
This anonymous operation must be the only defined operation.
Apollo iOS inserts __typename automatically when needed, please do not include it explicitly
Cannot query field "height" on type "Human".
There can only be one operation named "HeroName".
There can only be one operation named "HeroName".
There can only be one operation named "HeroName".
There can only be one operation named "HeroName".
Apollo iOS needs to be able to insert __typename when needed, please do not use it as an alias
Validation of GraphQL query document failed
```
[schema.json.txt](https://github.com/apollostack/apollo-codegen/files/640826/schema.json.txt)

**Comment by jtwigg** [comment]
Hmm.... I should keep plugging away. The .graphql files might be in a different location.

**Comment by martijnwalraven** [comment]
@jtwigg: It seems `**/*.graphql` is picking up a lot of `.graphql` files, and this is creating conflicts. All `.graphql` files are treated as one big query document, so operation and fragment names have to be unique.
