### ISSUE TITLE
Apollo GraphQL for VSCode: Do you need APOLLO_KEY for local use, for autocomplete and validation

### ISSUE THREAD

**Issue by ppseprus** [apollostack/apollo-codegen#2428]
Hey!

I'm trying to configure this extension so that I'd have autocomplete and validation on my queries. Unfortunately, with little luck. And the only last thing I can think of is that for some reason, the extension would require a developer key for that...

Do I need that for local use?

Thanks,
Peter

**Comment by sepsol** [comment]
I'm having the same issue as well. Any solutions?
