### ISSUE TITLE
[IR] Operations need to include the file path to each input file

### ISSUE THREAD

**Issue by felipecsl** [apollostack/apollo-codegen#38]
This has been discussed on https://github.com/apollostack/apollo-android/pull/83
On Android, the generated classes need to be organized by package, so that requires us to be able to determine the original file path for each of the `.graphql` files so we can use that to determine which package name to use. Organizing classes in packages is a very standard practice on Android  and this solution is inspired by how Sqldelight handles `.sq` files.

@martijnwalraven

**Comment by martijnwalraven** [comment]
@felipecsl: I just released version 0.10.1 of `apollo-codegen` with this feature added. You'll have to install it with `npm install -g apollo-codegen@next` for now however, because it also contains some changes to the Swift generator that are incompatible with the release version of Apollo iOS.

**Comment by felipecsl** [comment]
Whoa that was fast, thanks!
