### ISSUE TITLE
Keep top-level data field when storing the schema.json

### ISSUE THREAD

**Issue by marwanad** [apollostack/apollo-codegen#8]
Most (if not all) of the `schema.json` files provided online (such as [Relay](https://github.com/facebook/relay/blob/master/scripts/jest/testschema.json) for example) have the `data` field as the top-level field.

When downloading a schema through an introspection query using apollo-codegen, it only stores the `__schema` object in the json file.

IMO, keeping the data field should provide more flexibility for users, particularly in cases when someone doesn't go through the `download-schema` process.

This would also require minor modification to the checks in `loading.js` to support both cases.

I can push a fix if that's of interest.

**Comment by martijnwalraven** [comment]
Thanks for bringing this up. I think we should definitely follow convention here, so if you'd like to work on a fix that would be great!
